language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/android@sha256:83dfc4f5c23f2d8026ad2090b909c9a9ae840ff63a3efceb30eff3fc1cebc8fc /bin/sh -c "cd /ga && tools/uncrustify && git diff && git diff --quiet && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew lintProductionRelease && ./gradlew assembleProductionRelease"
    - os: osx
      osx_image: xcode11
      env:
        - ANDROID_HOME=/Users/travis/opt
        - SDK_FILENAME=sdk-tools-darwin-4333796.zip
      install:
        - brew cask uninstall java
        - brew tap adoptopenjdk/openjdk
        - brew cask install adoptopenjdk8
        - touch ~/.android/repositories.cfg
        - brew cask install android-sdk
        - brew install uncrustify
        - yes | sdkmanager "tools" "platform-tools" "build-tools;29.0.2" "platforms;android-29" "extras;android;m2repository" "extras;google;m2repository"
      script:
        - cd $HOME/build/blockstream/green_android && ./tools/uncrustify && git diff && git diff --quiet
        - cd $HOME/build/blockstream/green_android && ./gradlew lintProductionRelease
        - cd $HOME/build/blockstream/green_android && ./gradlew assembleProductionRelease
